// frontend/src/utils/languages.js
export const languages = {
  en: { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  hi: { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  bn: { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  te: { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  gu: { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' }
};

export const translations = {
  en: {
    platform: 'V-Ed Platform', home: 'Home', lessons: 'Lessons', games: 'Games', progress: 'Progress', profile: 'Profile',
    logout: 'Logout', points: 'Points',
    welcomeBack: 'Welcome back', readyToContinue: 'Ready to continue your learning journey?',
    class: 'Class', continueLearning: 'Continue Learning', playGames: 'Play Games',
    yourProgress: 'Your Progress', lessonsCompleted: 'Lessons Completed', gamesPlayed: 'Games Played',
    totalGames: 'Total Games', streak: 'Streak', days: 'days',
    lessonsForClass: 'Lessons for Class', forClass: 'for Class', allGrades: 'All Grades', allSubjects: 'All Subjects',
    mathematics: 'Mathematics', science: 'Science', english: 'English', hindi: 'Hindi',
    socialScience: 'Social Science', grade: 'Grade', subject: 'Subject', duration: 'Duration',
    minutes: 'minutes', startLesson: 'Start Lesson', reviewLesson: 'Review Lesson',
    noLessonsFound: 'No lessons found', tryDifferentSubject: 'Try selecting a different subject or check your grade settings.',
    math: 'Mathematics', science: 'Science', english: 'English', hindi: 'Hindi', social: 'Social Science',
    educationalGames: 'Educational Games', educationalGamesForClass: 'Educational Games for Class', playGame: 'Play Game', noGamesFound: 'No games found',
    noGamesAvailable: 'No games available for your class and selected subject yet.',
    easy: 'Easy', medium: 'Medium', hard: 'Hard', difficulty: 'Difficulty',
    progressTitle: 'Your Progress', totalPoints: 'Total Points', pointsEarned: 'Points earned',
    badgesEarned: 'Badges Earned', achievements: 'Achievements', learningStreak: 'Learning Streak',
    daysInRow: 'Days in a row', totalLearningTime: 'Total Learning Time', minutesSpent: 'Minutes spent',
    learningSummary: 'Your Learning Summary', name: 'Name', rollNumber: 'Roll Number',
    school: 'School', preferredLanguage: 'Preferred Language', yourBadges: 'Your Badges', outOf: 'out of',
    firstSteps: 'First Steps', firstStepsDesc: 'Completed your very first lesson',
    pointCollector: 'Point Collector', pointCollectorDesc: 'Earned 100 points',
    dedicatedLearner: 'Dedicated Learner', dedicatedLearnerDesc: 'Completed 5 lessons',
    gameMaster: 'Game Master', gameMasterDesc: 'Played 5 different games',
    mathWizard: 'Math Wizard', mathWizardDesc: 'Completed 5 Math lessons',
    scienceExplorer: 'Science Explorer', scienceExplorerDesc: 'Completed 5 Science lessons',
    languageExpert: 'Language Expert', languageExpertDesc: 'Completed 5 English or Hindi lessons',
    profileTitle: 'Profile', accountSettings: 'Account Settings', fullName: 'Full Name',
    rollNumberNote: 'Roll number cannot be changed', editProfile: 'Edit Profile',
    saveChanges: 'Save Changes', cancel: 'Cancel',
    loading: 'Loading...', backToHome: 'Back to Home', startLearning: 'Start Learning',
    lessonStarted: 'Lesson started! Keep learning!', gameStarted: 'Game started! Have fun learning!',
    profileUpdated: 'Profile updated successfully!', languageChanged: 'Language changed successfully!',
    pointsEarnedMsg: 'points earned!', offlineMessage: 'You\'re offline - Don\'t worry, you can still learn!',
    loginSuccess: 'Login successful! Welcome to V-Ed Platform! 🎉',
    loginFailed: 'Login failed. Please try again.',
    demoLoginSuccess: 'Demo login successful as',
    demoLoginFailed: 'Demo login failed. Please try again.',
    studentLogin: 'Student Login Portal',
    rollNumberLabel: 'Roll Number', rollNumberPlaceholder: 'e.g., STD001',
    fullNameLabel: 'Full Name', fullNamePlaceholder: 'e.g., Rahul Kumar',
    classLabel: 'Class', selectClass: 'Select your class',
    schoolLabel: 'School Name', schoolPlaceholder: 'e.g., Govt. Primary School',
    languageLabel: 'Preferred Language', newStudent: 'New student? Just fill in your details above!',
    tryDemo: 'Try Demo Account', demoAccounts: 'Demo Student Accounts',
    dataFetchFailed: 'Failed to load app data. Please try again.',
    navigatedTo: 'Navigated to',
    badgeEarned: 'Badge Earned:',
    gameStartFailed: 'Failed to start game.',
    lessonStartFailed: 'Failed to start/complete lesson.',
    profileUpdateFailed: 'Failed to update profile.',
    languageChangeFailed: 'Failed to change language.',
    alreadyHaveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    signIn: 'Sign In',
    studentRegistration: 'Student Registration',
    
    // New keys for LessonViewer and InteractiveQuestion
    lessonContentUnavailable: 'Lesson Content Unavailable',
    lessonContentBeingDeveloped: 'This lesson content is being developed. Please check back later!',
    backToLessons: 'Back to Lessons',
    previous: 'Previous',
    next: 'Next',
    completeLesson: 'Complete Lesson',
    takeQuiz: 'Take Quiz',
    lessonCompletedSuccessfully: 'Lesson completed successfully!',
    lessonAlreadyCompleted: 'Lesson already completed. Reviewing now.',
    lessonCompletionFailed: 'Failed to complete lesson.',
    quizStarted: 'Quiz started! Good luck!',
    correctAnswer: 'Correct! 🎉',
    incorrectAnswer: 'Incorrect. Try again!',

    // New keys for GameViewer
    backToGames: 'Back to Games',
    gameContentUnavailable: 'Game Content Unavailable',
    gameContentBeingDeveloped: 'This game content is being developed. Please check back later!',
    score: 'Score',
    question: 'Question',
    nextQuestion: 'Next Question',
    finishGame: 'Finish Game',
    gameOver: 'Game Over',
    finalScore: 'Final Score',
    percentageScore: 'Percentage Score',
    gameCompletedMsg: 'Game completed successfully!',
    gameAlreadyPlayed: 'Game already played. Reviewing now.',
    gameCompletionFailed: 'Failed to complete game.',
    pleaseAnswerQuestion: 'Please answer the current question before proceeding.',
  },
  
  hi: {
    platform: 'वी-एड प्लेटफॉर्म', home: 'होम', lessons: 'पाठ', games: 'खेल', progress: 'प्रगति', profile: 'प्रोफाइल',
    logout: 'लॉगआउट', points: 'अंक',
    welcomeBack: 'वापस स्वागत है', readyToContinue: 'अपनी सीखने की यात्रा जारी रखने के लिए तैयार हैं?',
    class: 'कक्षा', continueLearning: 'सीखना जारी रखें', playGames: 'खेल खेलें',
    yourProgress: 'आपकी प्रगति', lessonsCompleted: 'पूरे किए गए पाठ', gamesPlayed: 'खेले गए खेल',
    totalGames: 'कुल खेल', streak: 'लगातार', days: 'दिन',
    lessonsForClass: 'कक्षा के लिए पाठ', forClass: 'के लिए', allGrades: 'सभी कक्षाएं', allSubjects: 'सभी विषय',
    mathematics: 'गणित', science: 'विज्ञान', english: 'अंग्रेजी', hindi: 'हिंदी',
    socialScience: 'सामाजिक विज्ञान', grade: 'कक्षा', subject: 'विषय', duration: 'अवधि',
    minutes: 'मिनट', startLesson: 'पाठ शुरू करें', reviewLesson: 'पाठ की समीक्षा करें',
    noLessonsFound: 'कोई पाठ नहीं मिला', tryDifferentSubject: 'एक अलग विषय चुनने का प्रयास करें या अपनी कक्षा सेटिंग्स जांचें।',
    math: 'गणित', science: 'विज्ञान', english: 'अंग्रेजी', hindi: 'हिंदी', social: 'सामाजिक विज्ञान',
    educationalGames: 'शैक्षिक खेल', educationalGamesForClass: 'कक्षा के लिए शैक्षिक खेल', playGame: 'खेल खेलें', noGamesFound: 'कोई खेल नहीं मिला',
    noGamesAvailable: 'आपकी कक्षा और चयनित विषय के लिए अभी तक कोई खेल उपलब्ध नहीं है।',
    easy: 'आसान', medium: 'मध्यम', hard: 'कठिन', difficulty: 'कठिनाई',
    progressTitle: 'आपकी प्रगति', totalPoints: 'कुल अंक', pointsEarned: 'अर्जित अंक',
    badgesEarned: 'अर्जित बैज', achievements: 'उपलब्धियां', learningStreak: 'सीखने की लकीर',
    daysInRow: 'लगातार दिन', totalLearningTime: 'कुल सीखने का समय', minutesSpent: 'बिताए गए मिनट',
    learningSummary: 'आपका सीखने का सारांश', name: 'नाम', rollNumber: 'रोल नंबर',
    school: 'स्कूल', preferredLanguage: 'पसंदीदा भाषा', yourBadges: 'आपके बैज', outOf: 'में से',
    firstSteps: 'पहले कदम', firstStepsDesc: 'अपना पहला पाठ पूरा किया',
    pointCollector: 'अंक संग्राहक', pointCollectorDesc: '100 अंक अर्जित किए',
    dedicatedLearner: 'समर्पित शिक्षार्थी', dedicatedLearnerDesc: '5 पाठ पूरे किए',
    gameMaster: 'खेल मास्टर', gameMasterDesc: '5 अलग खेल खेले',
    mathWizard: 'गणित जादूगर', mathWizardDesc: '5 गणित के पाठ पूरे किए',
    scienceExplorer: 'विज्ञान खोजकर्ता', scienceExplorerDesc: '5 विज्ञान के पाठ पूरे किए',
    languageExpert: 'भाषा विशेषज्ञ', languageExpertDesc: '5 अंग्रेजी या हिंदी के पाठ पूरे किए',
    profileTitle: 'प्रोफाइल', accountSettings: 'खाता सेटिंग्स', fullName: 'पूरा नाम',
    rollNumberNote: 'रोल नंबर बदला नहीं जा सकता', editProfile: 'प्रोफाइल संपादित करें',
    saveChanges: 'परिवर्तन सहेजें', cancel: 'रद्द करें',
    loading: 'लोड हो रहा है...', backToHome: 'होम पर वापस जाएं', startLearning: 'सीखना शुरू करें',
    lessonStarted: 'पाठ शुरू हो गया! सीखते रहें!', gameStarted: 'खेल शुरू हो गया! मज़े से सीखें!',
    profileUpdated: 'प्रोफाइल सफलतापूर्वक अपडेट हो गया!', languageChanged: 'भाषा सफलतापूर्वक बदल गई!',
    pointsEarnedMsg: 'अंक अर्जित किए!', offlineMessage: 'आप ऑफ़लाइन हैं - चिंता न करें, आप अभी भी सीख सकते हैं!',
    loginSuccess: 'लॉगिन सफल! वी-एड प्लेटफॉर्म में आपका स्वागत है! 🎉',
    loginFailed: 'लॉगिन विफल। कृपया पुनः प्रयास करें।',
    demoLoginSuccess: 'डेमो लॉगिन सफल',
    demoLoginFailed: 'डेमो लॉगिन विफल। कृपया पुनः प्रयास करें।',
    studentLogin: 'छात्र लॉगिन पोर्टल',
    rollNumberLabel: 'रोल नंबर', rollNumberPlaceholder: 'जैसे, STD001',
    fullNameLabel: 'पूरा नाम', fullNamePlaceholder: 'जैसे, राहुल कुमार',
    classLabel: 'कक्षा', selectClass: 'अपनी कक्षा चुनें',
    schoolLabel: 'स्कूल का नाम', schoolPlaceholder: 'जैसे, सरकारी प्राथमिक विद्यालय',
    languageLabel: 'पसंदीदा भाषा', newStudent: 'नए छात्र? बस ऊपर अपनी जानकारी भरें!',
    tryDemo: 'डेमो अकाउंट आज़माएं', demoAccounts: 'डेमो छात्र खाते',
    dataFetchFailed: 'ऐप डेटा लोड करने में विफल। कृपया पुन: प्रयास करें।',
    navigatedTo: 'पर नेविगेट किया गया',
    badgeEarned: 'बैज अर्जित किया:',
    gameStartFailed: 'खेल शुरू करने में विफल।',
    lessonStartFailed: 'पाठ शुरू/पूरा करने में विफल।',
    profileUpdateFailed: 'प्रोफाइल अपडेट करने में विफल।',
    languageChangeFailed: 'भाषा बदलने में विफल।',
    alreadyHaveAccount: 'पहले से ही एक खाता है?',
    createAccount: 'खाता बनाएं',
    signIn: 'साइन इन करें',
    studentRegistration: 'छात्र पंजीकरण',
    
    // New keys for LessonViewer and InteractiveQuestion
    lessonContentUnavailable: 'पाठ सामग्री अनुपलब्ध',
    lessonContentBeingDeveloped: 'यह पाठ सामग्री विकसित की जा रही है। कृपया बाद में देखें!',
    backToLessons: 'पाठों पर वापस जाएं',
    previous: 'पिछला',
    next: 'अगला',
    completeLesson: 'पाठ पूरा करें',
    takeQuiz: 'प्रश्नोत्तरी दें',
    lessonCompletedSuccessfully: 'पाठ सफलतापूर्वक पूरा हुआ!',
    lessonAlreadyCompleted: 'पाठ पहले ही पूरा हो चुका है। अब समीक्षा कर रहे हैं।',
    lessonCompletionFailed: 'पाठ पूरा करने में विफल।',
    quizStarted: 'प्रश्नोत्तरी शुरू हुई! शुभकामनाएँ!',
    correctAnswer: 'सही! 🎉',
    incorrectAnswer: 'गलत। पुनः प्रयास करें!',

    // New keys for GameViewer
    backToGames: 'खेलों पर वापस जाएं',
    gameContentUnavailable: 'खेल सामग्री अनुपलब्ध',
    gameContentBeingDeveloped: 'यह खेल सामग्री विकसित की जा रही है। कृपया बाद में देखें!',
    score: 'स्कोर',
    question: 'प्रश्न',
    nextQuestion: 'अगला प्रश्न',
    finishGame: 'खेल समाप्त करें',
    gameOver: 'खेल खत्म',
    finalScore: 'अंतिम स्कोर',
    percentageScore: 'प्रतिशत स्कोर',
    gameCompletedMsg: 'खेल सफलतापूर्वक पूरा हुआ!',
    gameAlreadyPlayed: 'खेल पहले ही खेला जा चुका है। अब समीक्षा कर रहे हैं।',
    gameCompletionFailed: 'खेल पूरा करने में विफल।',
    pleaseAnswerQuestion: 'कृपया आगे बढ़ने से पहले वर्तमान प्रश्न का उत्तर दें।',
  },
  
  bn: {
    platform: 'ভি-এড প্ল্যাটফর্ম', home: 'হোম', lessons: 'পাঠ', games: 'গেম', progress: 'অগ্রগতি', profile: 'প্রোফাইল',
    logout: 'লগআউট', points: 'পয়েন্ট',
    welcomeBack: 'ফিরে আসার জন্য স্বাগতম', readyToContinue: 'আপনার শেখার যাত্রা চালিয়ে যেতে প্রস্তুত?',
    class: 'ক্লাস', continueLearning: 'শেখা চালিয়ে যান', playGames: 'গেম খেলুন',
    yourProgress: 'আপনার অগ্রগতি', lessonsCompleted: 'সম্পূর্ণ পাঠ', gamesPlayed: 'খেলা গেম',
    totalGames: 'মোট গেম', streak: 'ধারাবাহিকতা', days: 'দিন',
    lessonsForClass: 'ক্লাসের জন্য পাঠ', forClass: 'এর জন্য', allGrades: 'সব গ্রেড', allSubjects: 'সব বিষয়',
    mathematics: 'গণিত', science: 'বিজ্ঞান', english: 'ইংরেজি', hindi: 'হিন্দি',
    socialScience: 'সামাজিক বিজ্ঞান', grade: 'গ্রেড', subject: 'বিষয়', duration: 'সময়কাল',
    minutes: 'মিনিট', startLesson: 'পাঠ শুরু করুন', reviewLesson: 'পাঠ পর্যালোচনা করুন',
    noLessonsFound: 'কোন পাঠ পাওয়া যায়নি', tryDifferentSubject: 'একটি ভিন্ন বিষয় নির্বাচন করার চেষ্টা করুন বা আপনার গ্রেড সেটিংস পরীক্ষা করুন।',
    math: 'গণিত', science: 'বিজ্ঞান', english: 'ইংরেজি', hindi: 'হিন্দি', social: 'সামাজিক বিজ্ঞান',
    educationalGames: 'শিক্ষামূলক গেম', educationalGamesForClass: 'ক্লাসের জন্য শিক্ষামূলক গেম', playGame: 'গেম খেলুন', noGamesFound: 'কোন গেম পাওয়া যায়নি',
    noGamesAvailable: 'আপনার ক্লাস এবং নির্বাচিত বিষয়ের জন্য এখনও কোন গেম উপলব্ধ নেই।',
    easy: 'সহজ', medium: 'মাঝারি', hard: 'কঠিন', difficulty: 'কঠিনতা',
    progressTitle: 'আপনার অগ্রগতি', totalPoints: 'মোট পয়েন্ট', pointsEarned: 'অর্জিত পয়েন্ট',
    badgesEarned: 'অর্জিত ব্যাজ', achievements: 'অর্জন', learningStreak: 'শেখার ধারা',
    daysInRow: 'পরপর দিন', totalLearningTime: 'মোট শেখার সময়', minutesSpent: 'ব্যয়িত মিনিট',
    learningSummary: 'আপনার শেখার সারসংক্ষেপ', name: 'নাম', rollNumber: 'রোল নম্বর',
    school: 'স্কুল', preferredLanguage: 'পছন্দের ভাষা', yourBadges: 'আপনার ব্যাজ', outOf: 'এর মধ্যে',
    firstSteps: 'প্রথম পদক্ষেপ', firstStepsDesc: 'আপনার প্রথম পাঠ সম্পূর্ণ করেছেন',
    pointCollector: 'পয়েন্ট সংগ্রাহক', pointCollectorDesc: '১০০ পয়েন্ট অর্জন করেছেন',
    dedicatedLearner: 'নিবেদিত শিক্ষার্থী', dedicatedLearnerDesc: '৫টি পাঠ সম্পূর্ণ করেছেন',
    gameMaster: 'গেম মাস্টার', gameMasterDesc: '৫টি ভিন্ন গেম খেলেছেন',
    mathWizard: 'গণিত জাদুকর', mathWizardDesc: '৫টি গণিতের পাঠ সম্পূর্ণ করেছেন',
    scienceExplorer: 'বিজ্ঞান অনুসন্ধানকারী', scienceExplorerDesc: '৫টি বিজ্ঞানের পাঠ সম্পূর্ণ করেছেন',
    languageExpert: 'ভাষা বিশেষজ্ঞ', languageExpertDesc: '৫টি ইংরেজি বা হিন্দি পাঠ সম্পূর্ণ করেছেন',
    profileTitle: 'প্রোফাইল', accountSettings: 'অ্যাকাউন্ট সেটিংস', fullName: 'পূর্ণ নাম',
    rollNumberNote: 'রোল নম্বর পরিবর্তন করা যাবে না', editProfile: 'প্রোফাইল সম্পাদনা করুন',
    saveChanges: 'পরিবর্তন সংরক্ষণ করুন', cancel: 'বাতিল',
    loading: 'লোড হচ্ছে...', backToHome: 'হোমে ফিরে যান', startLearning: 'শেখা শুরু করুন',
    lessonStarted: 'পাঠ শুরু হয়েছে! শিখতে থাকুন!', gameStarted: 'গেম শুরু হয়েছে! আনন্দের সাথে শিখুন!',
    profileUpdated: 'প্রোফাইল সফলভাবে আপডেট হয়েছে!', languageChanged: 'ভাষা সফলভাবে পরিবর্তিত হয়েছে!',
    pointsEarnedMsg: 'পয়েন্ট অর্জিত!', offlineMessage: 'আপনি অফলাইনে আছেন - চিন্তা করবেন না, আপনি এখনও শিখতে পারেন!',
    loginSuccess: 'লগইন সফল! ভি-এড প্ল্যাটফর্মে স্বাগতম! 🎉',
    loginFailed: 'লগইন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    demoLoginSuccess: 'ডেমো লগইন সফল হয়েছে',
    demoLoginFailed: 'ডেমো লগইন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    studentLogin: 'ছাত্র লগইন পোর্টাল',
    rollNumberLabel: 'রোল নম্বর', rollNumberPlaceholder: 'যেমন, STD001',
    fullNameLabel: 'পূর্ণ নাম', fullNamePlaceholder: 'যেমন, রাহুল কুমার',
    classLabel: 'ক্লাস', selectClass: 'আপনার ক্লাস নির্বাচন করুন',
    schoolLabel: 'স্কুলের নাম', schoolPlaceholder: 'যেমন, সরকারি প্রাথমিক বিদ্যালয়',
    languageLabel: 'পছন্দের ভাষা', newStudent: 'নতুন ছাত্র? শুধু উপরের বিবরণ পূরণ করুন!',
    tryDemo: 'ডেমো অ্যাকাউন্ট ব্যবহার করুন', demoAccounts: 'ডেমো ছাত্র অ্যাকাউন্ট',
    dataFetchFailed: 'অ্যাপ ডেটা লোড করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    navigatedTo: 'এ নেভিগেট করা হয়েছে',
    badgeEarned: 'ব্যাজ অর্জিত:',
    gameStartFailed: 'গেম শুরু করতে ব্যর্থ।',
    lessonStartFailed: 'পাঠ শুরু/সম্পূর্ণ করতে ব্যর্থ।',
    profileUpdateFailed: 'প্রোফাইল আপডেট করতে ব্যর্থ।',
    languageChangeFailed: 'ভাষা পরিবর্তন করতে ব্যর্থ।',
    alreadyHaveAccount: 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    signIn: 'সাইন ইন করুন',
    studentRegistration: 'ছাত্র নিবন্ধন',
    
    // New keys for LessonViewer and InteractiveQuestion
    lessonContentUnavailable: 'পাঠের বিষয়বস্তু উপলব্ধ নয়',
    lessonContentBeingDeveloped: 'এই পাঠের বিষয়বস্তু তৈরি করা হচ্ছে। অনুগ্রহ করে পরে আবার দেখুন!',
    backToLessons: 'পাঠের তালিকায় ফিরে যান',
    previous: 'পূর্ববর্তী',
    next: 'পরবর্তী',
    completeLesson: 'পাঠ সম্পূর্ণ করুন',
    takeQuiz: 'কুইজ দিন',
    lessonCompletedSuccessfully: 'পাঠ সফলভাবে সম্পন্ন হয়েছে!',
    lessonAlreadyCompleted: 'পাঠ ইতিমধ্যে সম্পন্ন হয়েছে। এখন পর্যালোচনা করা হচ্ছে।',
    lessonCompletionFailed: 'পাঠ সম্পন্ন করতে ব্যর্থ।',
    quizStarted: 'কুইজ শুরু হয়েছে! শুভকামনা!',
    correctAnswer: 'সঠিক! 🎉',
    incorrectAnswer: 'ভুল। আবার চেষ্টা করুন!',
  },
  
  te: {
    platform: 'వి-ఎడ్ ప్లాట్‌ఫారమ్', home: 'హోమ్', lessons: 'పాఠాలు', games: 'ఆటలు', progress: 'పురోగతి', profile: 'ప్రొఫైల్',
    logout: 'లాగ్అవుట్', points: 'పాయింట్లు',
    welcomeBack: 'తిరిగి స్వాగతం', readyToContinue: 'మీ అభ్యాస ప్రయాణాన్ని కొనసాగించడానికి సిద్ధంగా ఉన్నారా?',
    class: 'క్లాస్', continueLearning: 'అభ్యాసం కొనసాగించండి', playGames: 'ఆటలు ఆడండి',
    yourProgress: 'మీ పురోగతి', lessonsCompleted: 'పూర్తయిన పాఠాలు', gamesPlayed: 'ఆడిన ఆటలు',
    totalGames: 'మొత్తం ఆటలు', streak: 'వరుస', days: 'రోజులు',
    lessonsForClass: 'క్లాస్ కోసం పాఠాలు', forClass: 'కోసం', allGrades: 'అన్ని గ్రేడ్లు', allSubjects: 'అన్ని విషయాలు',
    mathematics: 'గణితం', science: 'సైన్స్', english: 'ఇంగ్లీష్', hindi: 'హిందీ',
    socialScience: 'సామాజిక శాస్త్రం', grade: 'గ్రేడ్', subject: 'విషయం', duration: 'వ్యవధి',
    minutes: 'నిమిషాలు', startLesson: 'పాఠం ప్రారంభించండి', reviewLesson: 'పాఠం సమీక్షించండి',
    noLessonsFound: 'పాఠాలు కనుగొనబడలేదు', tryDifferentSubject: 'వేరే విషయం ఎంచుకోవడానికి ప్రయత్నించండి లేదా మీ గ్రేడ్ సెట్టింగ్లను తనిఖీ చేయండి.',
    math: 'గణితం', science: 'సైన్స్', english: 'ఇంగ్లీష్', hindi: 'హిందీ', social: 'సామాజిక శాస్త్రం',
    educationalGames: 'విద్యా ఆటలు', educationalGamesForClass: 'క్లాస్ కోసం విద్యా ఆటలు', playGame: 'ఆట ఆడండి', noGamesFound: 'ఆటలు కనుగొనబడలేదు',
    noGamesAvailable: 'మీ క్లాస్ మరియు ఎంచుకున్న విషయం కోసం ఇంకా ఆటలు అందుబాటులో లేవు.',
    easy: 'సులభం', medium: 'మధ్యమం', hard: 'కష్టం', difficulty: 'కష్టతనం',
    progressTitle: 'మీ పురోగతి', totalPoints: 'మొత్తం పాయింట్లు', pointsEarned: 'సంపాదించిన పాయింట్లు',
    badgesEarned: 'సంపాదించిన బ్యాడ్జ్‌లు', achievements: 'విజయాలు', learningStreak: 'అభ్యాస వరుస',
    daysInRow: 'వరుసగా రోజులు', totalLearningTime: 'మొత్తం అభ్యాస సమయం', minutesSpent: 'గడిపిన నిమిషాలు',
    learningSummary: 'మీ అభ్యాస సారాంశం', name: 'పేరు', rollNumber: 'రోల్ నంబర్',
    school: 'పాఠశాల', preferredLanguage: 'ప్రాధాన్య భాష', yourBadges: 'మీ బ్యాడ్జ్‌లు', outOf: 'లో',
    firstSteps: 'మొదటి అడుగులు', firstStepsDesc: 'మీ మొదటి పాఠం పూర్తి చేసారు',
    pointCollector: 'పాయింట్ కలెక్టర్', pointCollectorDesc: '100 పాయింట్లు సంపాదించారు',
    dedicatedLearner: 'అంకితభావ అభ్యాసకుడు', dedicatedLearnerDesc: '5 పాఠాలు పూర్తి చేసారు',
    gameMaster: 'గేమ్ మాస్టర్', gameMasterDesc: '5 వేర్వేరు ఆటలు ఆడారు',
    mathWizard: 'గణిత తాంత్రికుడు', mathWizardDesc: '5 గణిత పాఠాలు పూర్తి చేసారు',
    scienceExplorer: 'సైన్స్ అన్వేషకుడు', scienceExplorerDesc: '5 సైన్స్ పాఠాలు పూర్తి చేసారు',
    languageExpert: 'భాషా నిపుణుడు', languageExpertDesc: '5 ఇంగ్లీష్ లేదా హిందీ పాఠాలు పూర్తి చేసారు',
    profileTitle: 'ప్రొఫైల్', accountSettings: 'ఖాతా సెట్టింగ్లు', fullName: 'పూర్తి పేరు',
    rollNumberNote: 'రోల్ నంబర్ మార్చలేము', editProfile: 'ప్రొఫైల్ సవరించండి',
    saveChanges: 'మార్పులను సేవ్ చేయండి', cancel: 'రద్దు చేయండి',
    loading: 'లోడ్ అవుతోంది...', backToHome: 'హోమ్‌కు తిరిగి వెళ్లండి', startLearning: 'అభ్యాసం ప్రారంభించండి',
    lessonStarted: 'పాఠం ప్రారంభమైంది! అభ్యాసం కొనసాగించండి!', gameStarted: 'ఆట ప్రారంభమైంది! ఆనందంగా నేర్చుకోండి!',
    profileUpdated: 'ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ చేయబడింది!', languageChanged: 'భాష విజయవంతంగా మార్చబడింది!',
    pointsEarnedMsg: 'పాయింట్లు సంపాదించారు!', offlineMessage: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు - చింతించకండి, మీరు ఇంకా నేర్చుకోవచ్చు!',
    loginSuccess: 'లాగిన్ విజయవంతమైంది! వి-ఎడ్ ప్లాట్‌ఫారమ్‌కు స్వాగతం! 🎉',
    loginFailed: 'లాగిన్ విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    demoLoginSuccess: 'డెమో లాగిన్ విజయవంతమైంది',
    demoLoginFailed: 'డెమో లాగిన్ విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    studentLogin: 'విద్యార్థి లాగిన్ పోర్టల్',
    rollNumberLabel: 'రోల్ నంబర్', rollNumberPlaceholder: 'ఉదా., STD001',
    fullNameLabel: 'పూర్తి పేరు', fullNamePlaceholder: 'ఉదా., రాహుల్ కుమార్',
    classLabel: 'క్లాస్', selectClass: 'మీ క్లాస్‌ను ఎంచుకోండి',
    schoolLabel: 'పాఠశాల పేరు', schoolPlaceholder: 'ఉదా., ప్రభుత్వ ప్రాథమిక పాఠశాల',
    languageLabel: 'ప్రాధాన్య భాష', newStudent: 'కొత్త విద్యార్థి? పైన మీ వివరాలను పూరించండి!',
    tryDemo: 'డెమో ఖాతాను ప్రయత్నించండి', demoAccounts: 'డెమో విద్యార్థి ఖాతాలు',
    dataFetchFailed: 'యాప్ డేటాను లోడ్ చేయడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    navigatedTo: 'కి నావిగేట్ చేయబడింది',
    badgeEarned: 'బ్యాడ్జ్ సంపాదించబడింది:',
    gameStartFailed: 'ఆటను ప్రారంభించడంలో విఫలమైంది.',
    lessonStartFailed: 'పాఠాన్ని ప్రారంభించడంలో/పూర్తి చేయడంలో విఫలమైంది.',
    profileUpdateFailed: 'ప్రొఫైల్‌ను అప్‌డేట్ చేయడంలో విఫలమైంది.',
    languageChangeFailed: 'భాషను మార్చడంలో విఫలమైంది.',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    createAccount: 'ఖాతాను సృష్టించండి',
    signIn: 'సైన్ ఇన్ చేయండి',
    studentRegistration: 'విద్యార్థి నమోదు',
    
    // New keys for LessonViewer
    lessonContentUnavailable: 'పాఠం కంటెంట్ అందుబాటులో లేదు',
    lessonContentBeingDeveloped: 'ఈ పాఠం కంటెంట్ అభివృద్ధి చేయబడుతోంది. దయచేసి తర్వాత మళ్లీ తనిఖీ చేయండి!',
    backToLessons: 'పాఠాలకు తిరిగి వెళ్ళు',
    previous: 'మునుపటి',
    next: 'తదుపరి',
    completeLesson: 'పాఠం పూర్తి చేయండి',
    takeQuiz: 'క్విజ్ తీసుకోండి',
    lessonCompletedSuccessfully: 'పాఠం విజయవంతంగా పూర్తయింది!',
    lessonAlreadyCompleted: 'పాఠం ఇప్పటికే పూర్తయింది. ఇప్పుడు సమీక్షిస్తోంది.',
    lessonCompletionFailed: 'పాఠం పూర్తి చేయడంలో విఫలమైంది.',
    quizStarted: 'క్విజ్ ప్రారంభమైంది! శుభాకాంక్షలు!',
    correctAnswer: 'సరైనది! 🎉',
    incorrectAnswer: 'తప్పు. మళ్ళీ ప్రయత్నించండి!',
  },
  
  gu: {
    platform: 'વી-એડ પ્લેટફોર્મ', home: 'હોમ', lessons: 'પાઠ', games: 'રમતો', progress: 'પ્રગતિ', profile: 'પ્રોફાઇલ',
    logout: 'લૉગઆઉટ', points: 'પોઇન્ટ',
    welcomeBack: 'પાછા આવવા બદલ આપનું સ્વાગત છે', readyToContinue: 'તમારી શીખવાની યાત્રા ચાલુ રાખવા તૈયાર છો?',
    class: 'વર્ગ', continueLearning: 'શીખવાનું ચાલુ રાખો', playGames: 'રમતો રમો',
    yourProgress: 'તમારી પ્રગતિ', lessonsCompleted: 'પૂર્ણ થયેલા પાઠ', gamesPlayed: 'રમાયેલી રમતો',
    totalGames: 'કુલ રમતો', streak: 'સતત', days: 'દિવસો',
    lessonsForClass: 'વર્ગ માટે પાઠ', forClass: 'માટે', allGrades: 'બધા ગ્રેડ', allSubjects: 'બધા વિષયો',
    mathematics: 'ગણિત', science: 'વિજ્ઞાન', english: 'અંગ્રેજી', hindi: 'હિન્દી',
    socialScience: 'સામાજિક વિજ્ઞાન', grade: 'ગ્રેડ', subject: 'વિષય', duration: 'અવધિ',
    minutes: 'મિનિટ', startLesson: 'પાઠ શરૂ કરો', reviewLesson: 'પાઠની સમીક્ષા કરો',
    noLessonsFound: 'કોઈ પાઠ મળ્યો નથી', tryDifferentSubject: 'કોઈ અલગ વિષય પસંદ કરવાનો પ્રયાસ કરો અથવા તમારી ગ્રેડ સેટિંગ્સ તપાસો.',
    math: 'ગણિત', science: 'વિજ્ઞાન', english: 'અંગ્રેજી', hindi: 'હિન્દી', social: 'સામાજિક વિજ્ઞાન',
    educationalGames: 'શૈક્ષણિક રમતો', educationalGamesForClass: 'વર્ગ માટે શૈક્ષણિક રમતો', playGame: 'રમત રમો', noGamesFound: 'કોઈ રમત મળી નથી',
    noGamesAvailable: 'તમારા વર્ગ અને પસંદ કરેલા વિષય માટે હજુ સુધી કોઈ રમત ઉપલબ્ધ નથી.',
    easy: 'સરળ', medium: 'મધ્યમ', hard: 'મુશ્કેલ', difficulty: 'મુશ્કેલી',
    progressTitle: 'તમારી પ્રગતિ', totalPoints: 'કુલ પોઇન્ટ', pointsEarned: 'કમાયેલા પોઇન્ટ',
    badgesEarned: 'મેળવેલા બેજેસ', achievements: 'સિદ્ધિઓ', learningStreak: 'શીખવાની સતત',
    daysInRow: 'સતત દિવસો', totalLearningTime: 'કુલ શીખવાનો સમય', minutesSpent: 'ખર્ચ કરેલી મિનિટો',
    learningSummary: 'તમારો શીખવાનો સારાંશ', name: 'નામ', rollNumber: 'રોલ નંબર',
    school: 'શાળા', preferredLanguage: 'પસંદીદા ભાષા', yourBadges: 'તમારા બેજેસ', outOf: 'માંથી',
    firstSteps: 'પ્રથમ પગલાં', firstStepsDesc: 'તમારો પ્રથમ પાઠ પૂર્ણ કર્યો',
    pointCollector: 'પોઇન્ટ કલેક્ટર', pointCollectorDesc: '100 પોઇન્ટ કમાયા',
    dedicatedLearner: 'સમર્પિત શીખનાર', dedicatedLearnerDesc: '5 પાઠ પૂર્ણ કર્યા',
    gameMaster: 'ગેમ માસ્ટર', gameMasterDesc: '5 અલગ રમતો રમ્યા',
    mathWizard: 'ગણિત વિઝાર્ડ', mathWizardDesc: '5 ગણિતના પાઠ પૂર્ણ કર્યા',
    scienceExplorer: 'વિજ્ઞાન સંશોધક', scienceExplorerDesc: '5 વિજ્ઞાનના પાઠ પૂર્ણ કર્યા',
    languageExpert: 'ભાષા નિષ્ણાત', languageExpertDesc: '5 અંગ્રેજી અથવા હિન્દી પાઠ પૂર્ણ કર્યા',
    profileTitle: 'પ્રોફાઇલ', accountSettings: 'એકાઉન્ટ સેટિંગ્સ', fullName: 'પૂરું નામ',
    rollNumberNote: 'રોલ નંબર બદલી શકાતો નથી', editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
    saveChanges: 'ફેરફારો સાચવો', cancel: 'રદ કરો',
    loading: 'લોડિંગ...', backToHome: 'હોમ પર પાછા', startLearning: 'શીખવાનું શરૂ કરો',
    lessonStarted: 'પાઠ શરૂ થયો! શીખતા રહો!', gameStarted: 'રમત શરૂ થઈ! શીખવામાં મજા કરો!',
    profileUpdated: 'પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ!', languageChanged: 'ભાષા સફળતાપૂર્વક બદલાઈ!',
    pointsEarnedMsg: 'પોઇન્ટ કમાયા!', offlineMessage: 'તમે ઑફલાઇન છો - ચિંતા કરશો નહીં, તમે હજી પણ શીખી શકો છો!',
    loginSuccess: 'લૉગિન સફળ! V-Ed પ્લેટફોર્મમાં આપનું સ્વાગત છે! 🎉',
    loginFailed: 'લૉગિન નિષ્ફળ. કૃપા કૃપા કરીને ફરી પ્રયાસ કરો.',
    demoLoginSuccess: 'ડેમો લૉગિન સફળ',
    demoLoginFailed: 'ડેમો લૉગિન નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    studentLogin: 'વિદ્યાર્થી લૉગિન પોર્ટલ',
    rollNumberLabel: 'રોલ નંબર', rollNumberPlaceholder: 'દા.ત., STD001',
    fullNameLabel: 'પૂરું નામ', fullNamePlaceholder: 'દા.ત., રાહુલ કુમાર',
    classLabel: 'વર્ગ', selectClass: 'તમારો વર્ગ પસંદ કરો',
    schoolLabel: 'શાળાનું નામ', schoolPlaceholder: 'દા.ત., સરકારી પ્રાથમિક શાળા',
    languageLabel: 'પસંદીદા ભાષા', newStudent: 'નવા વિદ્યાર્થી? ફક્ત ઉપર તમારી વિગતો ભરો!',
    tryDemo: 'ડેમો એકાઉન્ટ અજમાવો', demoAccounts: 'ડેમો વિદ્યાર્થી એકાઉન્ટ્સ',
    dataFetchFailed: 'એપ્લિકેશન ડેટા લોડ કરવામાં નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    navigatedTo: 'પર નેવિગેટ કર્યું',
    badgeEarned: 'બેજ કમાયા:',
    gameStartFailed: 'રમત શરૂ કરવામાં નિષ્ફળ.',
    lessonStartFailed: 'પાઠ શરૂ/પૂર્ણ કરવામાં નિષ્ફળ.',
    profileUpdateFailed: 'પ્રોફાઇલ અપડેટ કરવામાં નિષ્ફળ.',
    languageChangeFailed: 'ભાષા બદલવામાં નિષ્ફળ.',
    alreadyHaveAccount: 'પહેલેથી જ એક એકાઉન્ટ છે?',
    createAccount: 'એકાઉન્ટ બનાવો',
    signIn: 'સાઇન ઇન કરો',
    studentRegistration: 'વિદ્યાર્થી નોંધણી',
    
    // New keys for LessonViewer
    lessonContentUnavailable: 'પાઠ કન્ટેન્ટ ઉપલબ્ધ નથી',
    lessonContentBeingDeveloped: 'આ પાઠ કન્ટેન્ટ વિકસાવવામાં આવી રહ્યું છે. કૃપા કરીને પછીથી ફરી તપાસ કરો!',
    backToLessons: 'પાઠ પર પાછા',
    previous: 'પહેલું',
    next: 'આગલું',
    completeLesson: 'પાઠ પૂર્ણ કરો',
    takeQuiz: 'ક્વિઝ લો',
    lessonCompletedSuccessfully: 'પાઠ સફળતાપૂર્વક પૂર્ણ થયો!',
    lessonAlreadyCompleted: 'પાઠ પહેલેથી જ પૂર્ણ થયો છે. હવે સમીક્ષા કરી રહ્યા છીએ.',
    lessonCompletionFailed: 'પાઠ પૂર્ણ કરવામાં નિષ્ફળ.',
    quizStarted: 'ક્વિઝ શરૂ થઈ! શુભેચ્છાઓ!',
    correctAnswer: 'સાચું! 🎉',
    incorrectAnswer: 'ખોટું. ફરી પ્રયાસ કરો!',
  }
};

// EXPORT the getTranslation function
export const getTranslation = (key, langCode = 'en') => {
  return translations[langCode]?.[key] || translations.en[key] || key;
};

// EXPORT the getCurrentLanguage function
export const getCurrentLanguage = () => {
  const savedUser = localStorage.getItem('vedStudent');
  if (savedUser) {
    try {
      const userData = JSON.parse(savedUser);
      return userData.language || 'en';
    } catch (error) {
      return 'en';
    }
  }
  return 'en';
};

// EXPORT the showNotification function
export const showNotification = (message, type = 'success', duration = 3000) => {
  const notification = document.createElement('div');
  notification.className = `app-notification ${type}`;
  notification.textContent = message;

  let notificationContainer = document.querySelector('.notification-container');
  if (!notificationContainer) {
    notificationContainer = document.createElement('div');
    notificationContainer.className = 'notification-container';
    document.body.appendChild(notificationContainer);
  }
  
  notificationContainer.appendChild(notification);
  
  setTimeout(() => {
    if (notification.parentNode) {
      notification.parentNode.removeChild(notification);
    }
    // Only remove the container if it's empty
    if (notificationContainer.children.length === 0) {
      notificationContainer.remove();
    }
  }, duration);
};
